<head>
    <?php
    load_css(array(
        "assets/css/scss/header_homepage.css",
        "assets/css/scss/body_homepage.css",
        "assets/css/scss/footer_homepage.css",
    ));
    load_js(array(
        "assets/js/jquery-3.6.0.min.js"
    ))
    ?>
</head>
